# This workflow will build source and binary distributions based
# on the current repository tag. Artifacts are then uploaded to
# PyPI and a GitHub Release is created.
#

name: Create a Release and Publish to PyPI

on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Build a binary wheel and a source tarball
        run: |
          pip install wheel
          python setup.py bdist_wheel

      - name: Check version match
        id: check_version
        run: |
          echo "FUSION_VERSION=1.0.9" >> $GITHUB_ENV

      - name: Create a Github Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided automatically by Actions
        with:
          tag_name: v1.0.9
          release_name: Fusion - Release ${{ github.ref }} (${{ github.event.repository.updated_at}})
          body: |
            Publishing release as [purefusion-${{ env.FUSION_VERSION }}](https://pypi.org/project/purefusion/)
          draft: false
          prerelease: false

      - name: Upload Release Asset (tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/purefusion-${{ env.FUSION_VERSION }}.tar.gz
          asset_name: purefusion-${{ env.FUSION_VERSION }}.tar.gz
          asset_content_type: application/x-tar
